version: "2"

run:
  timeout: 5m

linters:
  default: none

  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - revive

  settings:
    revive:
      rules:
        - name: errorf
        - name: unexported-return
        - name: receiver-naming
        - name: indent-error-flow
        - name: if-return

  exclusions:
    generated: lax
    warn-unused: true
    presets:
      - comments
      - std-error-handling
      - common-false-positives
      - legacy

    rules:
      - path: autoupdate/
        linters:
          - revive

      - path: ".*_windows\\.go"
        linters:
          - revive

      - path: ".*_darwin\\.go"
        linters:
          - revive

      - text: "nolint:errcheck"
        linters:
          - errcheck

    paths:
      - autoupdate/
      - ".*_windows\\.go"
      - ".*_darwin\\.go"

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  uniq-by-line: false
  new: true
  new-from-merge-base: main
  new-from-rev: HEAD
  new-from-patch: ""
  whole-files: true
  fix: true
