version: 2
project_name: tnr

before:
  hooks: []

builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}

signs:
  - id: macos-sign
    cmd: codesign
    args:
      - "--force"
      - "--timestamp"
      - "--options"
      - "runtime"
      - "--sign"
      - "{{ .Env.DEVELOPER_ID_APP }}"
      - "{{ .ArtifactPath }}"
    artifacts: binary
    ids: [tnr]
    env:
      - "PATH=/usr/bin:/usr/local/bin"

before_publish:
  - ids: [tnr]
    artifacts: [binary]
    output: true
    cmd: |
      bash -euxo pipefail <<'EOF'
      echo "🟢 before_publish: start"
      echo "pwd=$(pwd)"
      OUTDIR="dist"
      BIN="{{ .ArtifactPath }}"
      ARCH="{{ .Arch }}"
      VERSION="{{ .Version }}"
      NAME="{{ .ProjectName }}"

      echo "OUTDIR=$OUTDIR"
      echo "BIN=$BIN"
      echo "ARCH=$ARCH VERSION=$VERSION NAME=$NAME"

      # Skip PKG building if SKIP_PKG_BUILD is set (for local testing)
      if [ "${SKIP_PKG_BUILD:-}" = "true" ]; then
        echo "⚠️  Skipping PKG build (SKIP_PKG_BUILD=true)"
        exit 0
      fi

      test -f "$BIN" || { echo "❌ Missing BIN: $BIN"; exit 1; }

      /usr/bin/which /usr/bin/pkgbuild
      /usr/bin/which /usr/bin/productsign
      /usr/bin/which /usr/sbin/pkgutil

      # Optional, helpful debug:
      /usr/bin/security find-identity -v -p codesigning || true

      WORK="$(/usr/bin/mktemp -d -t tnr.pkg.${ARCH}.XXXXXX)"
      PKGROOT="$WORK/root"
      /bin/mkdir -p "$PKGROOT/usr/local/bin"
      /usr/bin/install -m 0755 "$BIN" "$PKGROOT/usr/local/bin/tnr"

      PKG_UNSIGNED="$OUTDIR/${NAME}_${VERSION}_darwin_${ARCH}_unsigned.pkg"
      PKG_SIGNED="$OUTDIR/${NAME}_${VERSION}_darwin_${ARCH}.pkg"

      echo "🔧 Building unsigned: $PKG_UNSIGNED"
      /usr/bin/pkgbuild \
        --root "$PKGROOT" \
        --identifier "com.thundercompute.tnr" \
        --version "$VERSION" \
        --install-location "/" \
        "$PKG_UNSIGNED"

      test -f "$PKG_UNSIGNED" || { echo "❌ pkgbuild did not create $PKG_UNSIGNED"; ls -al "$OUTDIR"; exit 1; }

      # Validate and sign PKG (required for production releases)
      if [ -z "${DEVELOPER_ID_INSTALLER:-}" ]; then
        echo "❌ ERROR: DEVELOPER_ID_INSTALLER not set!"
        echo "   PKG signing is required for production releases."
        echo "   Please set DEVELOPER_ID_INSTALLER in your environment."
        /bin/rm -rf "$WORK"
        exit 1
      elif [[ "$DEVELOPER_ID_INSTALLER" =~ "Your Name" ]] || [[ "$DEVELOPER_ID_INSTALLER" =~ "TEAMID" ]]; then
        echo "❌ ERROR: DEVELOPER_ID_INSTALLER contains placeholder values!"
        echo "   Current value: $DEVELOPER_ID_INSTALLER"
        echo "   Please update with your actual certificate identity."
        echo "   Run: security find-identity -p codesigning -v"
        /bin/rm -rf "$WORK"
        exit 1
      fi

      echo "🔏 Signing PKG with: $DEVELOPER_ID_INSTALLER"
      if ! /usr/bin/productsign --sign "$DEVELOPER_ID_INSTALLER" "$PKG_UNSIGNED" "$PKG_SIGNED" 2>&1; then
        echo "❌ ERROR: PKG signing failed!"
        echo "   Certificate: $DEVELOPER_ID_INSTALLER"
        echo "   Verify certificate is valid: security find-identity -p codesigning -v"
        /bin/rm -rf "$WORK"
        exit 1
      fi
      
      if [ ! -f "$PKG_SIGNED" ]; then
        echo "❌ ERROR: Signed PKG was not created: $PKG_SIGNED"
        /bin/ls -al "$OUTDIR"
        /bin/rm -rf "$WORK"
        exit 1
      fi
      
      echo "🔎 Verifying PKG signature..."
      if ! /usr/sbin/pkgutil --check-signature "$PKG_SIGNED"; then
        echo "❌ ERROR: PKG signature verification failed!"
        /bin/rm -rf "$WORK"
        exit 1
      fi
      
      echo "✅ PKG signed successfully: $PKG_SIGNED"
      /bin/rm -f "$PKG_UNSIGNED"

      /bin/rm -rf "$WORK"
      echo "📦 OUTDIR contents after build:"
      /bin/ls -al "$OUTDIR"

      echo "🔍 find any .pkg under repo:"
      /usr/bin/find . -maxdepth 4 -name "*.pkg" -print -ls || true

      echo "✅ before_publish: done"
      EOF




# notarize:
#   macos:
#     - enabled: true
#       ids: [tnr]
#       sign:
#         certificate: "{{ .Env.MACOS_SIGN_P12_PATH }}"
#         password: "{{ .Env.MACOS_CERT_PASSWORD }}"
#       notarize:
#         issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
#         key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
#         key: "{{ .Env.MACOS_NOTARY_KEY_PATH }}"
#         wait: true
#         timeout: 20m

archives:
  - id: archive
    ids: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

sboms:
  - id: sbom
    artifacts: archive

blobs:
  - provider: s3
    # if: '{{ eq .Os "darwin" }}'
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    directory: "tnr/releases/{{ .Version }}/macos"
    # ids: [archive, checksum, sbom]
    extra_files:
      - glob: "dist/*_darwin_*.pkg"

brews:
  - name: tnr
    ids: [archive]
    repository:
      owner: Thunder-Compute
      name: homebrew-tnr
      token: "{{ .Env.GH_PAT }}"
    url_template: "https://{{ .Env.TNR_S3_BUCKET }}.s3.{{ .Env.AWS_REGION }}.amazonaws.com/tnr/releases/{{ .Version }}/{{ .ArtifactName }}"
    directory: Formula
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    description: "Thunder Compute CLI"
    homepage: "https://github.com/Thunder-Compute/thunder-cli"
    license: MIT
    test: |
      system "#{bin}/tnr", "--version"
    install: |
      bin.install "tnr"

release:
  disable: false
  draft: false
  prerelease: auto
  skip_upload: true

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
