# GoReleaser configuration for Windows builds
# This file handles building and publishing Windows packages (.msi)
# Run by GitHub Actions in the windows_release job
# See: .github/workflows/release.yml

version: 2
project_name: tnr

before:
  hooks: []

# Sign MSI files before publishing
before_publish:
  hooks:
    - cmd: powershell -ExecutionPolicy Bypass -Command "$msiFiles = Get-ChildItem -Path dist -Filter *.msi -Recurse; if ($msiFiles.Count -eq 0) { Write-Error 'No MSI files found to sign'; exit 1 }; $signtool = Get-ChildItem -Path 'C:\\Program Files (x86)\\Windows Kits\\10\\bin\\*\\x64\\signtool.exe' -ErrorAction SilentlyContinue | Select-Object -First 1; if (-not $signtool) { Write-Error 'signtool.exe not found. Please install Windows SDK.'; exit 1 }; Write-Host \"Using signtool: $($signtool.FullName)\"; foreach ($msi in $msiFiles) { Write-Host \"Signing: $($msi.FullName)\"; & $signtool.FullName sign /sha1 $env:CERT_THUMBPRINT /fd sha256 /tr $env:TIMESTAMP_SERVER /td sha256 /debug /v $msi.FullName; if ($LASTEXITCODE -ne 0) { Write-Error \"Failed to sign $($msi.Name)\"; exit 1 }; Write-Host \"Successfully signed: $($msi.Name)\"; & $signtool.FullName verify /pa /v $msi.FullName; if ($LASTEXITCODE -ne 0) { Write-Warning \"Signature verification failed for $($msi.Name)\" } }"
      env:
        - CERT_THUMBPRINT={{ .Env.CERT_THUMBPRINT }}
        - TIMESTAMP_SERVER={{ .Env.TIMESTAMP_SERVER }}

# Build configuration for Windows binaries
builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}

# Archive configuration (.zip for Windows)
archives:
  - id: archive
    ids: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [zip]
    files:
      - LICENSE
      - README.md

# Checksum file for Windows artifacts
checksum:
  name_template: "checksums-windows.txt"

# Windows MSI installer configuration
# Uses WiX v4 to create professional Windows installers
# See: packaging/windows/app.wxs for installer definition
msi:
  - id: tnr-msi
    name: "tnr-{{ .Version }}-{{ .Arch }}"
    wxs: ./packaging/windows/app.wxs
    ids: [tnr]
    goamd64: v1
    version: v4
    replace: false
    mod_timestamp: "{{ .CommitTimestamp }}"

# Software Bill of Materials (SBOM) generation
sboms:
  - id: sbom
    artifacts: archive

# S3 upload configuration
# Uploads archives and MSI installers to S3 for distribution
# extra_files needed here because MSI files aren't automatically included in blobs
blobs:
  - provider: s3
    if: '{{ eq .Os "windows" }}'
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    directory: "tnr/releases/{{ .Version }}/windows"
    extra_files:
      - glob: "dist/*.msi"

# GitHub release configuration
# extra_files needed here to include MSI installers in GitHub releases
release:
  disable: false
  draft: false
  prerelease: auto
  extra_files:
    - glob: "dist/*.msi"

# Changelog generation settings
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

# Scoop package manager integration
# Automatically updates the Scoop bucket with new releases
# Users can install via: scoop bucket add tnr https://github.com/Thunder-Compute/scoop-bucket; scoop install tnr
scoops:
  - name: tnr
    ids: [archive]
    url_template: "https://{{ .Env.TNR_S3_BUCKET }}.s3.{{ .Env.AWS_REGION }}.amazonaws.com/tnr/releases/{{ .Version }}/windows/{{ .ArtifactName }}"
    homepage: "https://github.com/Thunder-Compute/thunder-cli"
    description: "Thunder Compute CLI"
    license: MIT
    repository:
      owner: Thunder-Compute
      name: scoop-bucket
      token: "{{ .Env.GH_PAT }}"

# Windows Package Manager (winget) integration
# Automatically creates PR to winget-pkgs repository for new releases
# Users can install via: winget install Thunder.tnr
winget:
  - name: tnr
    ids: [archive]
    publisher: Thunder Compute
    short_description: "Thunder Compute CLI"
    license: MIT
    publisher_url: "https://www.thundercompute.com"
    package_identifier: Thunder.tnr
    repository:
      owner: Thunder-Compute
      name: winget-pkgs
      branch: "tnr-{{ .Version }}"
      token: "{{ .Env.GH_PAT }}"