version: 2
project_name: tnr

before:
  hooks: []

builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}

nfpms:
  - id: tnr-packages
    package_name: tnr
    builds: [tnr]
    vendor: Thunder Compute
    homepage: https://github.com/Thunder-Compute/thunder-cli
    maintainer: Thunder Compute <support@thundercompute.com>
    description: |
      Thunder Compute CLI - Manage Thunder GPU compute instances
    license: MIT
    formats:
      - deb
      - rpm
      - apk
    bindir: /usr/bin
    contents:
      - src: LICENSE
        dst: /usr/share/doc/tnr/LICENSE
      - src: README.md
        dst: /usr/share/doc/tnr/README.md
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

archives:
  - id: archive
    ids: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums-linux.txt"

sboms:
  - id: sbom
    artifacts: archive

blobs:
  - provider: s3
    if: '{{ eq .Os "linux" }}'
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    directory: "tnr/releases/{{ .Version }}/linux"
    extra_files:
      - glob: "dist/*.deb"
      - glob: "dist/*.rpm"
      - glob: "dist/*.apk"

before_publish:
  - cmd: |
      bash -lc '
        printf "{\"version\":\"%s\"}\n" "{{ .Version }}" > dist/latest.json &&
        aws s3 cp dist/latest.json "s3://{{ .Env.TNR_S3_BUCKET }}/tnr/releases/latest.json" \
          --cache-control "public, max-age=120" \
          --content-type "application/json"
      '

release:
  disable: false
  draft: false
  prerelease: auto

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
