# GoReleaser configuration for Windows builds
# This file handles building and publishing Windows packages (.msi)
# Run by the monorepo's cli-release workflow
# See: .github/workflows/cli-release.yml
# Releases are created on Thunder-Compute/thunder-cli

version: 2
project_name: tnr

before:
  hooks:
    - pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/embed-windows-icon.ps1

# Build configuration for Windows binaries
builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.SentryDSN={{ .Env.SENTRY_DSN }}
    hooks:
      post:
        - >-
          pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/sign-windows-artifact.ps1
          -ArtifactPath "{{ .Path }}"
        - >-
          pwsh -NoProfile -ExecutionPolicy Bypass -File ./scripts/build-msi.ps1
          -BinaryPath "{{ .Path }}" -Arch "{{ .Arch }}" -Version "{{ .Version }}" -ProjectName "{{ .ProjectName }}"

# Archive configuration (.zip for Windows)
archives:
  - id: archive
    ids: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [zip]
    files:
      - LICENSE
      - README.md

# Checksum file for Windows artifacts
checksum:
  name_template: "checksums-windows.txt"

# Software Bill of Materials (SBOM) generation
sboms:
  - id: sbom
    artifacts: archive

# GCS upload configuration
# Uploads archives and MSI installers to Google Cloud Storage for distribution
# extra_files needed here because MSI files aren't automatically included in blobs
blobs:
  - provider: gs
    bucket: "{{ .Env.GCP_BUCKET }}"
    directory: "tnr/releases/{{ .Version }}/windows"
    cache_control:
      - public
      - max-age=31536000
      - immutable
    ids:
      - archive
      - checksum
    extra_files:
      - glob: "dist/*.msi"

# GitHub release configuration

# extra_files needed here to include MSI installers in GitHub releases
release:
  github:
    owner: Thunder-Compute
    name: thunder-cli
  disable: false
  draft: false
  prerelease: auto
  extra_files:
    - glob: "dist/*.msi"

# Changelog generation settings

changelog:
  disable: true

# TODO: Re-enable once GH_PAT has write access to these repos
# # Scoop package manager integration
# # Automatically updates the Scoop bucket with new releases
# # Users can install via: scoop bucket add tnr https://github.com/Thunder-Compute/scoop-bucket; scoop install tnr
# scoops:
#   - name: tnr
#     ids: [archive]
#     url_template: "https://storage.googleapis.com/thunder-cli/tnr/releases/{{ .Version }}/windows/{{ .ArtifactName }}"
#     homepage: "https://github.com/Thunder-Compute/thunder-cli"
#     description: "Thunder Compute CLI"
#     license: MIT
#     repository:
#       owner: Thunder-Compute
#       name: scoop-bucket
#       token: "{{ .Env.GH_PAT }}"
#
# # Windows Package Manager (winget) integration
# # Automatically creates PR to winget-pkgs repository for new releases
# # Users can install via: winget install Thunder.tnr
# winget:
#   - name: tnr
#     ids: [archive]
#     publisher: Thunder Compute
#     short_description: "Thunder Compute CLI"
#     license: MIT
#     publisher_url: "https://www.thundercompute.com"
#     package_identifier: Thunder.tnr
#     repository:
#       owner: Thunder-Compute
#       name: winget-pkgs
#       branch: "tnr-{{ .Version }}"
#       token: "{{ .Env.GH_PAT }}"
