# https://goreleaser.com/customization/blob/

version: 2

project_name: tnr

before:
  hooks: []

builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{.Version}}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{.Commit}}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{.Date}}

archives:
  - id: archive
    builds: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

nfpms:
  - id: macos_pkg
    builds:
      - tnr
    formats: [pkg]
    vendor: "Thunder Compute"
    maintainer: "Thunder Compute <support@thundercompute.com>"
    description: "Thunder Compute CLI - manage cloud instances, deployments, and configs."
    license: MIT
    homepage: "https://thundercompute.com"
    package_name: "tnr"
    bindir: /usr/local/bin
    replacements:
      darwin: macos
    formats_overrides:
      darwin: pkg
    dependencies: []

checksum:
  name_template: "checksums.txt"

# Disable GitHub release
release:
  disable: true

# Upload to S3 only
blobs:
  - provider: s3
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    directory: "tnr/releases/{{ .Version }}"
    ids: [archive, checksum, macos_pkg]

