version: 2
project_name: tnr

before:
  hooks: []

builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}

signs:
  - id: macos-sign
    cmd: codesign
    args:
      - "--force"
      - "--timestamp"
      - "--options"
      - "runtime"
      - "--sign"
      - "{{ .Env.DEVELOPER_ID_APP }}"
      - "{{ .ArtifactPath }}"
    artifacts: binary
    ids: [tnr]
    env:
      - "PATH=/usr/bin:/usr/local/bin"

before_publish:
  - ids: [tnr]
    artifacts: binary
    output: true
    cmd: |
      bash -euo pipefail << 'EOF'
      # Only package on macOS artifacts
      if [ "{{ .Os }}" != "darwin" ]; then exit 0; fi

      BIN="{{ .ArtifactPath }}"
      ARCH="{{ .Arch }}"
      VERSION="{{ .Version }}"
      NAME="{{ .ProjectName }}"

      # Stage a simple payload that installs to /usr/local/bin
      WORK="dist/pkg-${ARCH}"
      PKGROOT="$WORK/root"
      mkdir -p "$PKGROOT/usr/local/bin"
      install -m 0755 "$BIN" "$PKGROOT/usr/local/bin/tnr"

      PKG_UNSIGNED="dist/${NAME}_${VERSION}_darwin_${ARCH}_unsigned.pkg"
      PKG_SIGNED="dist/${NAME}_${VERSION}_darwin_${ARCH}.pkg"

      # Build component package
      pkgbuild \
        --root "$PKGROOT" \
        --identifier "com.thundercompute.tnr" \
        --version "$VERSION" \
        --install-location "/" \
        "$PKG_UNSIGNED"

      # Sign the installer package with your Developer ID Installer cert
      productsign \
        --sign "{{ .Env.DEVELOPER_ID_INSTALLER }}" \
        "$PKG_UNSIGNED" "$PKG_SIGNED"

      pkgutil --check-signature "$PKG_SIGNED" || exit 1
      rm -rf "$WORK" "$PKG_UNSIGNED"

      # Optional: notarize + staple if envs are present
      if [ -n "${MACOS_NOTARY_KEY_ID:-}" ] && [ -n "${MACOS_NOTARY_ISSUER_ID:-}" ] && [ -n "${MACOS_NOTARY_KEY_PATH:-}" ]; then
        xcrun notarytool submit "$PKG_SIGNED" \
          --key "$MACOS_NOTARY_KEY_PATH" \
          --key-id "$MACOS_NOTARY_KEY_ID" \
          --issuer "$MACOS_NOTARY_ISSUER_ID" \
          --wait
        xcrun stapler staple "$PKG_SIGNED"
      fi
      EOF

# notarize:
#   macos:
#     - enabled: true
#       ids: [tnr]
#       sign:
#         certificate: "{{ .Env.MACOS_SIGN_P12_PATH }}"
#         password: "{{ .Env.MACOS_CERT_PASSWORD }}"
#       notarize:
#         issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
#         key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
#         key: "{{ .Env.MACOS_NOTARY_KEY_PATH }}"
#         wait: true
#         timeout: 20m

archives:
  - id: archive
    ids: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

sboms:
  - id: sbom
    artifacts: archive

blobs:
  - provider: s3
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    directory: "tnr/releases/{{ .Version }}"
    ids: [archive, checksum, sbom]
    extra_files:
      - glob: "dist/{{ .ProjectName }}_{{ .Version }}_darwin_*.pkg"

brews:
  - name: tnr
    ids: [archive]
    repository:
      owner: Thunder-Compute
      name: homebrew-tnr
      token: "{{ .Env.GH_PAT }}"
    url_template: "https://{{ .Env.TNR_S3_BUCKET }}.s3.{{ .Env.AWS_REGION }}.amazonaws.com/tnr/releases/{{ .Version }}/{{ .ArtifactName }}"
    directory: Formula
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    description: "Thunder Compute CLI"
    homepage: "https://github.com/Thunder-Compute/thunder-cli"
    license: MIT
    test: |
      system "#{bin}/tnr", "--version"
    install: |
      bin.install "tnr"

release:
  disable: false
  draft: false
  prerelease: auto
  skip_upload: true

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
