version: 2
project_name: tnr

before:
  hooks: []

builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [darwin]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}
    hooks:
      post:
        - |
          bash -c '
          set -euo pipefail;
          ARCH="{{ .Arch }}";
          NAME="{{ .ProjectName }}";
          VERSION="{{ .Version }}";

          # Find the built binary for this arch (handles _v1 / _v8.0 suffixes)
          BIN="$(ls dist/${NAME}_darwin_${ARCH}_*/${NAME} 2>/dev/null | head -n1)";
          test -f "$BIN";

          # Sign the binary before packaging
          if [ -n "${DEVELOPER_ID_APP:-}" ]; then
            echo "🔏 Signing binary: $BIN"
            /usr/bin/codesign --force --timestamp --options runtime \
              --sign "$DEVELOPER_ID_APP" "$BIN"
            
            # Verify the signature
            /usr/bin/codesign --verify --verbose "$BIN"
            echo "✅ Binary signed successfully"
          else
            echo "⚠️  Skipping binary signing (DEVELOPER_ID_APP not set)"
          fi

          WORK="$(/usr/bin/mktemp -d -t ${NAME}.pkg.${ARCH}.XXXXXX)";
          trap "rm -rf \"$WORK\"" EXIT;
          PKGROOT="$WORK/root";
          /bin/mkdir -p "$PKGROOT/usr/local/bin";
          /usr/bin/install -m 0755 "$BIN" "$PKGROOT/usr/local/bin/${NAME}";

          PKG_UNSIGNED="dist/${NAME}_${VERSION}_darwin_${ARCH}_unsigned.pkg";
          PKG_SIGNED="dist/${NAME}_${VERSION}_darwin_${ARCH}.pkg";

          /usr/bin/pkgbuild --root "$PKGROOT" \
            --identifier "com.thundercompute.${NAME}" \
            --version "$VERSION" \
            --install-location "/" \
            "$PKG_UNSIGNED";

          if [ -n "${DEVELOPER_ID_INSTALLER:-}" ]; then
            /usr/bin/productsign --sign "$DEVELOPER_ID_INSTALLER" "$PKG_UNSIGNED" "$PKG_SIGNED" \
            && rm -f "$PKG_UNSIGNED" \
            || mv "$PKG_UNSIGNED" "$PKG_SIGNED";
            /usr/sbin/pkgutil --check-signature "$PKG_SIGNED" || true;
          else
            mv "$PKG_UNSIGNED" "$PKG_SIGNED";
          fi

          # Notarize the .pkg file after signing
          if [ -n "${MACOS_NOTARY_KEY_PATH:-}" ] && [ -n "${MACOS_NOTARY_KEY_ID:-}" ] && [ -n "${MACOS_NOTARY_ISSUER_ID:-}" ]; then
            echo "🔐 Notarizing package: $PKG_SIGNED"
            
            # Submit for notarization (notarytool blocks until complete with --wait)
            if xcrun notarytool submit "$PKG_SIGNED" \
              --key "$MACOS_NOTARY_KEY_PATH" \
              --key-id "$MACOS_NOTARY_KEY_ID" \
              --issuer "$MACOS_NOTARY_ISSUER_ID" \
              --wait \
              --timeout 20m; then
              
              echo "✅ Notarization successful!"
              # Staple the notarization ticket to the package
              xcrun stapler staple "$PKG_SIGNED" || echo "⚠️  Stapling failed (ticket may not be available yet)"
            else
              echo "❌ Notarization failed!"
              exit 1
            fi
          else
            echo "⚠️  Skipping notarization (credentials not configured)"
          fi

          ls -lh dist/*.pkg;
          '

# builds:
#   - id: tnr
#     main: ./main.go
#     binary: tnr
#     env:
#       - CGO_ENABLED=0
#     goos: [darwin]
#     goarch: [amd64, arm64]
#     ldflags:
#       - -s -w
#       - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
#       - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
#       - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}

signs:
  - id: macos-sign
    cmd: codesign
    args:
      - "--force"
      - "--timestamp"
      - "--options"
      - "runtime"
      - "--sign"
      - "{{ .Env.DEVELOPER_ID_APP }}"
      - "{{ .ArtifactPath }}"
    artifacts: binary
    ids: [tnr]
    env:
      - "PATH=/usr/bin:/usr/local/bin"

# after:
#   hooks:
#     - cmd: |
#         bash -Eeuo pipefail <<'PKG'
#         set -x
#         echo "🟢 Creating PKGs in dist/"
        
#         for ARCH in amd64 arm64; do
#           if [ "$ARCH" = "amd64" ]; then
#             BIN="dist/tnr_darwin_amd64_v1/tnr"
#           else
#             BIN="dist/tnr_darwin_arm64_v8.0/tnr"
#           fi
          
#           VERSION="{{ .Version }}"
#           NAME="{{ .ProjectName }}"
          
#           test -f "$BIN" || { echo "❌ Missing BIN: $BIN"; exit 1; }
          
#           WORK="$(/usr/bin/mktemp -d -t tnr.pkg.${ARCH}.XXXXXX)"
#           trap 'rm -rf "$WORK"' EXIT
#           PKGROOT="$WORK/root"
#           /bin/mkdir -p "$PKGROOT/usr/local/bin"
#           /usr/bin/install -m 0755 "$BIN" "$PKGROOT/usr/local/bin/tnr"
          
#           PKG_UNSIGNED="dist/${NAME}_${VERSION}_darwin_${ARCH}_unsigned.pkg"
#           PKG_SIGNED="dist/${NAME}_${VERSION}_darwin_${ARCH}.pkg"
          
#           echo "🔧 Building unsigned PKG: $PKG_UNSIGNED"
#           /usr/bin/pkgbuild \
#             --root "$PKGROOT" \
#             --identifier "com.thundercompute.tnr" \
#             --version "$VERSION" \
#             --install-location "/" \
#             "$PKG_UNSIGNED"
          
#           if [ -n "${DEVELOPER_ID_INSTALLER:-}" ]; then
#             echo "🔏 Signing PKG with: $DEVELOPER_ID_INSTALLER"
#             if /usr/bin/productsign --sign "$DEVELOPER_ID_INSTALLER" "$PKG_UNSIGNED" "$PKG_SIGNED"; then
#               /usr/sbin/pkgutil --check-signature "$PKG_SIGNED"
#               rm -f "$PKG_UNSIGNED"
#               echo "✅ Signed PKG: $PKG_SIGNED"
#             else
#               echo "⚠️  Signing failed; keeping unsigned"
#               mv "$PKG_UNSIGNED" "$PKG_SIGNED"
#             fi
#           else
#             echo "⚠️  No DEVELOPER_ID_INSTALLER; producing unsigned PKG"
#             mv "$PKG_UNSIGNED" "$PKG_SIGNED"
#           fi
#         done
        
#         echo "📦 PKGs created:"
#         ls -lh dist/*.pkg
#         PKG



# notarize:
#   macos:
#     - enabled: true
#       ids: [tnr]
#       sign:
#         certificate: "{{ .Env.MACOS_SIGN_P12_PATH }}"
#         password: "{{ .Env.MACOS_CERT_PASSWORD }}"
#       notarize:
#         issuer_id: "{{ .Env.MACOS_NOTARY_ISSUER_ID }}"
#         key_id: "{{ .Env.MACOS_NOTARY_KEY_ID }}"
#         key: "{{ .Env.MACOS_NOTARY_KEY_PATH }}"
#         wait: true
#         timeout: 20m

archives:
  - id: archive
    ids: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

sboms:
  - id: sbom
    artifacts: archive

blobs:
  - provider: s3
    # if: '{{ eq .Os "darwin" }}'
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    directory: "tnr/releases/{{ .Version }}/macos"
    # ids: [archive, checksum, sbom]
    extra_files:
      - glob: "dist/*.pkg"

brews:
  - name: tnr
    ids: [archive]
    repository:
      owner: Thunder-Compute
      name: homebrew-tnr
      token: "{{ .Env.GH_PAT }}"
    url_template: "https://{{ .Env.TNR_S3_BUCKET }}.s3.{{ .Env.AWS_REGION }}.amazonaws.com/tnr/releases/{{ .Version }}/{{ .ArtifactName }}"
    directory: Formula
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    description: "Thunder Compute CLI"
    homepage: "https://github.com/Thunder-Compute/thunder-cli"
    license: MIT
    test: |
      system "#{bin}/tnr", "--version"
    install: |
      bin.install "tnr"

release:
  disable: false
  draft: false
  prerelease: auto
  extra_files:
    - glob: "dist/*.pkg"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
