version: 2

project_name: tnr

before:
  hooks: []

builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}

signs:
  - id: macos-sign
    cmd: codesign
    args:
      - "--force"
      - "--timestamp"
      - "--options"
      - "runtime"
      - "--sign"
      - "{{ .Env.DEVELOPER_ID_APP }}"
      - "{{ .ArtifactPath }}"
    artifacts: all
    env:
      - "PATH=/usr/bin:/usr/local/bin"

notarize:
  macos:
    # - enabled: '{{ isEnvSet "MACOS_SIGN_CERTIFICATE" }}'  # Ensures this is enabled only if cert is set
    - enabled: true
      ids:
        - tnr
      # sign:
      #   certificate: "{{.Env.MACOS_SIGN_CERTIFICATE}}"    # The certificate base64 or file path
      #   password: "{{.Env.MACOS_SIGN_PASSWORD}}"          # Password for the certificate
      notarize:
        issuer_id: "{{.Env.MACOS_NOTARY_ISSUER_ID}}"      # Issuer ID from Apple Developer
        key_id: "{{.Env.MACOS_NOTARY_KEY_ID}}"            # Key ID from Apple Developer
        key: "{{.Env.MACOS_NOTARY_KEY}}"                  # The notarization private key, base64'd or file path
        wait: true                                        # Wait for the notarization to complete
        timeout: 20m                                      # Set timeout for notarization

archives:
  - id: archive
    ids: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

msi:
  - id: tnr-msi
    name: "tnr-{{ .MsiArch }}"
    wxs: ./packaging/windows/app.wxs
    ids: [archive]
    goamd64: v1
    version: v4
    replace: false
    mod_timestamp: "{{ .CommitTimestamp }}"
    disable: '{{ ne .Runtime.Goos "windows" }}'

before_publish:
  - cmd: |
      bash -lc '
        printf "{\"version\":\"%s\"}\n" "{{ .Version }}" > dist/latest.json &&
        aws s3 cp dist/latest.json "s3://{{ .Env.TNR_S3_BUCKET }}/tnr/releases/latest.json" \
          --cache-control "public, max-age=120" \
          --content-type "application/json"
      '

release:
  disable: false
  draft: false
  prerelease: auto

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

sboms:
  - id: sbom
    artifacts: archive

blobs:
  - provider: s3
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    directory: "tnr/releases/{{ .Version }}"
    ids: [archive, checksum, sbom, tnr-msi]
  

brews:
  - name: tnr
    ids: [archive]
    repository:
      owner: Thunder-Compute
      name: homebrew-tnr
      token: "{{ .Env.GH_PAT }}"
    url_template: "https://{{ .Env.TNR_S3_BUCKET }}.s3.{{ .Env.AWS_REGION }}.amazonaws.com/tnr/releases/{{ .Version }}/{{ .ArtifactName }}"
    directory: Formula
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com
    description: "Thunder Compute CLI"
    homepage: "https://github.com/Thunder-Compute/thunder-cli"
    license: MIT
    test: |
      system "#{bin}/tnr", "--version"
    install: |
      bin.install "tnr"

# scoops:
#   - name: tnr
#     ids: [archive]
#     url_template: "https://{{ .Env.TNR_S3_BUCKET }}.s3.{{ .Env.AWS_REGION }}.amazonaws.com/tnr/releases/{{ .Version }}/{{ .ArtifactName }}"
#     homepage: "https://github.com/Thunder-Compute/thunder-cli"
#     description: "Thunder Compute CLI"
#     license: MIT
#     repository:
#       owner: Thunder-Compute
#       name: scoop-bucket
#       token: "{{ .Env.GH_PAT }}"
#       pull_request:
#         enabled: true

# winget:
#   - name: tnr
#     ids: [archive]
#     publisher: Thunder
#     short_description: "Thunder Compute CLI"
#     license: MIT
#     publisher_url: "https://www.thundercompute.com"
#     package_identifier: Thunder.tnr
#     url_template: "https://{{ .Env.TNR_S3_BUCKET }}.s3.{{ .Env.AWS_REGION }}.amazonaws.com/tnr/releases/{{ .Version }}/{{ .ArtifactName }}"
#     repository:
#       owner: Thunder-Compute
#       name: winget-pkgs
#       branch: "tnr-{{ .Version }}"
#       token: "{{ .Env.GH_PAT }}"
#       pull_request:
#         enabled: true
#         base:
#           owner: microsoft
#           name: winget-pkgs
#           branch: master
#     commit_author:
#       name: goreleaser
#       email: goreleaser@users.noreply.github.com
