version: 2
project_name: tnr

before:
  hooks: []

builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{ .Version }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{ .Commit }}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{ .Date }}

archives:
  - id: archive
    ids: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    formats: [zip]
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums-windows.txt"

msi:
  - id: tnr-msi
    name: "tnr-{{ .Version }}-{{ .Arch }}"
    wxs: ./packaging/windows/app.wxs
    ids: [tnr]
    goamd64: v1
    version: v4
    replace: false
    mod_timestamp: "{{ .CommitTimestamp }}"

sboms:
  - id: sbom
    artifacts: archive

blobs:
  - provider: s3
    if: '{{ eq .Os "windows" }}'
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    directory: "tnr/releases/{{ .Version }}/windows"
    extra_files:
      - glob: "dist/*.msi"

release:
  disable: false
  draft: false
  prerelease: auto
  extra_files:
    - glob: "dist/*.msi"

changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
