project_name: tnr

before:
  hooks: []

builds:
  - id: tnr
    main: ./main.go
    binary: tnr
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    flags: []
    ldflags:
      - -s -w
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildVersion={{.Version}}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildCommit={{.Commit}}
      - -X github.com/Thunder-Compute/thunder-cli/internal/version.BuildDate={{.Date}}

archives:
  - id: archive
    builds: [tnr]
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'

sboms:
  - artifacts: [archive]
    id: cyclonedx
    formats: [cyclonedx]

attestations:
  - id: provenance
    predicate: slsa_provenance
    artifacts: [archive, checksum]

release:
  github:
    owner: Thunder-Compute
    name: thunder-cli
  draft: false
  prerelease: auto

brews:
  - name: tnr
    repository:
      owner: Thunder-Compute
      name: homebrew-tnr
      token: "{{ .Env.GITHUB_TOKEN }}"
    description: "Thunder Compute CLI"
    homepage: https://github.com/Thunder-Compute/thunder-cli
    license: MIT
    test: |
      system "#{bin}/tnr", "--version"
    install: |
      bin.install "tnr"
    commit_author:
      name: goreleaser
      email: goreleaser@users.noreply.github.com

scoop:
  bucket:
    owner: Thunder-Compute
    name: scoop-bucket
    token: "{{ .Env.GITHUB_TOKEN }}"
  homepage: https://github.com/Thunder-Compute/thunder-cli
  description: Thunder Compute CLI
  license: MIT
  commit_author:
    name: goreleaser
    email: goreleaser@users.noreply.github.com

winget:
  publisher: Thunder
  short_description: Thunder Compute CLI
  publisher_url: https://github.com/Thunder-Compute/thunder-cli
  package_identifier: Thunder.tnr
  package_name: tnr
  tags:
    - thunder
    - cli
  author: Thunder
  commit_author:
    name: goreleaser
    email: goreleaser@users.noreply.github.com

nfpms:
  - id: linux-packages
    package_name: tnr
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Arch }}"
    maintainer: Thunder Compute <noreply@thunder.invalid>
    description: Thunder Compute CLI
    license: MIT
    homepage: https://github.com/Thunder-Compute/thunder-cli
    replaces:
      - tnr
    recommends: []
    suggests: []
    conflicts: []
    contents: []
    formats: [deb, rpm]
    bindir: /usr/bin
    section: default
    priority: optional
    scripts: {}
    umask: 0022
    overrides:
      deb:
        signature: null
      rpm:
        signature: null

blobs:
  - provider: s3
    bucket: "{{ .Env.TNR_S3_BUCKET }}"
    region: "{{ .Env.AWS_REGION }}"
    folder: "tnr/releases/{{ .Version }}"
    ids: [archive, checksum]


